---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kokidurecom/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp blog-details.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp portfolio-details.html $DEPLOYPATH
    - /bin/cp service-details.html $DEPLOYPATH
    - /bin/cp starter-page.html $DEPLOYPATH
